-- Elam core database schema.
-- Detailed access policies are added in Phase 2B. RLS is enabled here so all
-- browser access remains denied by default until those policies exist.

create type public.user_role as enum ('learner', 'instructor', 'admin');
create type public.course_status as enum ('draft', 'in_review', 'published', 'archived');
create type public.order_status as enum ('pending', 'paid', 'failed', 'refunded');
create type public.media_status as enum ('absent', 'uploading', 'processing', 'ready', 'failed');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null check (length(btrim(full_name)) > 0),
  avatar_url text,
  role public.user_role not null default 'learner',
  headline text,
  bio text,
  created_at timestamptz not null default now()
);

create table public.platform_settings (
  id integer primary key default 1 check (id = 1),
  instructor_direct_publish boolean not null default false,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles (id)
);

insert into public.platform_settings (id) values (1);

create table public.courses (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (length(btrim(slug)) > 0),
  department text not null default 'EE' check (length(btrim(department)) > 0),
  course_code text,
  title text not null check (length(btrim(title)) > 0),
  subtitle text,
  description text,
  price_halalas integer not null check (price_halalas >= 0),
  currency char(3) not null default 'SAR' check (currency = 'SAR'),
  status public.course_status not null default 'draft',
  cover_url text,
  instructor_id uuid not null references public.profiles (id),
  created_at timestamptz not null default now(),
  published_at timestamptz
);

create index courses_published_status_idx
  on public.courses (status)
  where status = 'published';

create index courses_instructor_id_idx
  on public.courses (instructor_id);

create table public.modules (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses (id) on delete cascade,
  title text not null check (length(btrim(title)) > 0),
  position integer not null check (position > 0),
  constraint modules_course_position_key
    unique (course_id, position) deferrable initially deferred
);

create table public.lessons (
  id uuid primary key default gen_random_uuid(),
  module_id uuid not null references public.modules (id) on delete cascade,
  title text not null check (length(btrim(title)) > 0),
  position integer not null check (position > 0),
  video_asset_id text,
  duration_seconds integer check (duration_seconds >= 0),
  is_free_preview boolean not null default false,
  media_status public.media_status not null default 'absent',
  created_at timestamptz not null default now(),
  constraint lessons_module_position_key
    unique (module_id, position) deferrable initially deferred
);

create index lessons_module_id_idx
  on public.lessons (module_id);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id),
  course_id uuid not null references public.courses (id),
  amount_halalas integer not null check (amount_halalas >= 0),
  currency char(3) not null default 'SAR' check (currency = 'SAR'),
  status public.order_status not null default 'pending',
  moyasar_payment_id text unique,
  failure_reason text,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  refunded_at timestamptz
);

create index orders_user_id_idx
  on public.orders (user_id);

create index orders_status_created_at_idx
  on public.orders (status, created_at desc);

create table public.enrollments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id),
  course_id uuid not null references public.courses (id),
  order_id uuid unique references public.orders (id),
  granted_at timestamptz not null default now(),
  expires_at timestamptz,
  constraint enrollments_user_course_key unique (user_id, course_id)
);

create index enrollments_course_id_idx
  on public.enrollments (course_id);

create table public.lesson_progress (
  user_id uuid not null references public.profiles (id) on delete cascade,
  lesson_id uuid not null references public.lessons (id) on delete cascade,
  last_position_seconds integer not null default 0 check (last_position_seconds >= 0),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_id)
);

create index lesson_progress_lesson_id_idx
  on public.lesson_progress (lesson_id);

create table public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles (id),
  action text not null check (length(btrim(action)) > 0),
  subject text,
  detail jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.platform_settings enable row level security;
alter table public.courses enable row level security;
alter table public.modules enable row level security;
alter table public.lessons enable row level security;
alter table public.orders enable row level security;
alter table public.enrollments enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.admin_audit_log enable row level security;
